blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/pep8speaks-org/pep8speaks/issues
    about: You can ask and answer questions here.
  - name: Documentation
    url: https://pep8speaks.org/
    about: The PEP8Speaks documentation.
